server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///essy_mybatis
    username: root
    password: root
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5  #心跳间隔时间
      lease-expiration-duration-in-seconds: 15 #过期时间
